# Generated by Django 5.0.1 on 2024-01-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comment_bid_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='starting_price',
            new_name='price',
        ),
    ]
